export default {
  UPLOAD: "UPLOAD",
  COIN: "coins",
  RATER: "A&R Intern",
  SUBMIT_MUSIC_QUEUE: "Submit Music to the Queue",
  TITLE: "Title",
  UPLOAD_FILE: "Upload MP3 File (must have .mp3 extension)",
  BROWSE: "browse",
  FILE: "MP3 file",
  SIZE: "15MB max",
  YOUTUBE_LINK: "Paste Youtube Link",
  GENRES_STYLES: "Genres & Styles",
  SEARCH_GENRES: "Search for Genres",
  SEARCH_STYLES: "Search for Style",
  PROMO_CODE: "Promo Code",
  RATING_HEADER: "Select # of Ratings",
  PLAN_A: "Plan A",
  LISTENERS: "Listeners",
  PREMIERE: "Premiere",
  CARD_INFORMATION: "Card Information",
  NAME: "Name",
  CARD_NUMBER: "Card Number",
  CARD_CVC: "CVC",
  CARD_MONTH: "MM/YY",
  PAYMENT_OPTIONS: "Payment Options",
  ORDER_NOW: "Order Now",
  PAYMENT_SUCESSFUL: "Payment Successful",
  DONE: "Done",
  RETRY: "Retry",
  UNSUCESSFUL: "Payment Unsuccessful",
};
