export default {
    LOCATION: "Location",
    CHOOSE_CITY: "Enter your Location",
    ENTER_BIO: "Enter a biography",
    BIO: "Bio",
    SEND_ME: " Send me",
    ENTER_SEND_ME: "Enter Send me",
    ROLES: "Roles",
    SEARCH_ROLE: "Search for Roles",
    GENRES: "Genres",
    SEARCH_GENRES: "Search for Genres",
    STYLES: "Styles",
    SEARCH_STYLES: "Search for Styles",
    FILER_RATE: "Filter Rate",
    PRICE: "Price",
    SET_YOUR_PRICE: "Set your price",
    SET_YOUR_PRICE_CONTENT: "* Set the amount you’d like to charge to rate and review one track *",
    MAX_WORDS: "160 Words Max",
    SAVE: "Save",
}